# Generated by Django 4.2.1 on 2023-05-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('EventCategory', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Payment', models.IntegerField(null=True)),
                ('Status', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=300)),
                ('Organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.event')),
                ('User_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
