# Generated by Django 4.2.1 on 2023-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('First_Name', models.CharField(default=None, max_length=50, null=True)),
                ('Last_Name', models.CharField(default=None, max_length=50, null=True)),
                ('Age', models.IntegerField(default=0)),
                ('Mob_No', models.IntegerField(default=0)),
                ('Gender', models.CharField(default=None, max_length=7, null=True)),
            ],
        ),
    ]
